name: "NowSecure"

on:
  workflow_dispatch:
    branches: [ main ]
  pull_request:
    branches: [main]
    
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build App 
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: iOSVoteApp.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MY_MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          configuration: "Release"
          export-method: "ad-hoc"
          
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: /Users/runner/work/iOSVoteApp/iOSVoteApp/output.ipa
          retention-days: 3  

  scan:
    runs-on: ubuntu-latest
    outputs:
      report_id: ${{ steps.upload.outputs.report_id }}
    # The stage that builds the application.
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      # Replace with whatever pulls the application file before we upload.
      - name: Download application
        uses: actions/download-artifact@v2
        with:
          # Generated in the "build" stage.
          name: app

      - id: upload
        name: NowSecure upload app
        uses: nowsecure/nowsecure-action/upload-app@v3
        with:
          platform_token: ${{ secrets.NS_TOKEN }}
          # TODO: Replace application path.
          app_file: "output.ipa"
          # TODO: Replace the Group ID.
          group_id: "e487b673-6d93-4131-b4ec-b4d072916962"
          
  process:
    if: ${{ needs.scan.outputs.report_id }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    # The above stage we introduced.
    needs: scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      - name: NowSecure download report
        uses: nowsecure/nowsecure-action/convert-sarif@v3
        timeout-minutes: 90
        with:
          report_id: ${{ needs.scan.outputs.report_id }}
          platform_token: ${{ secrets.NS_TOKEN }}
          # TODO: Replace the Group ID.
          group_id: "e487b673-6d93-4131-b4ec-b4d072916962"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: NowSecure.sarif
          
      - name: Save SARIF File
        uses: actions/upload-artifact@v2
        with:
          name: NowSecure SARIF
          path: NowSecure.sarif
          retention-days: 14
