name: "NS Test"

on:
  workflow_dispatch:
    branches: [ main ]
 
    
    
jobs:
          
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      - name: NowSecure download report
        uses: nowsecure/nowsecure-action/convert-sarif@v3
        timeout-minutes: 90
        with:
          report_id: "fd99390c-ad3f-46a6-a445-fd4b42fa4bb4"
          platform_token: ${{ secrets.NS_TOKEN }}
          # TODO: Replace the Group ID.
          group_id: "e487b673-6d93-4131-b4ec-b4d072916962"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: NowSecure.sarif
          
      - name: Save SARIF File
        uses: actions/upload-artifact@v2
        with:
          name: NowSecure SARIF
          path: NowSecure.sarif
          retention-days: 14
